import dotenv from "dotenv";
dotenv.config();

const {
    PORT,
    MONGODB_URL,
    NODE_ENV,
    CLIENT_URL,
    SENDER_EMAIL,
    NODEMAILER_PASSKEY,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    AWS_REGION,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    S3_BUCKET_NAME,
    STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET,   
} = process.env;

export {
    PORT,
    MONGODB_URL,
    NODE_ENV,
    CLIENT_URL,
    SENDER_EMAIL,
    NODEMAILER_PASSKEY,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    AWS_REGION,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    S3_BUCKET_NAME,
    STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET,
};