export const GenderOptions: string[] = ["Male", "Female", "Other"];
export const BloodTypes: string[] = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];
export const DiseaseOptions: string[] = [
  "none",
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Cancer",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Heart Disease",
  "Stroke",
  "Alzheimer's Disease",
  "Parkinson's Disease",
  "Hepatitis",
  "HIV/AIDS",
  "Tuberculosis",
  "Malaria",
  "Dengue Fever",
  "Influenza",
  "Pneumonia",
  "Arthritis",
  "Epilepsy",
  "Multiple Sclerosis",
  "Anemia",
  "Leukemia",
  "Lymphoma",
  "Migraine",
  "Depression",
  "Anxiety Disorders",
  "COVID-19",
  "Chikungunya",
  "Zika Virus",
  "Meningitis",
];
